config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path, notice: "Flat was successfully saved"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flat_path(@flat), notice: "Flat was successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :adress, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit Flat: <%= @flat.name %></h1>

<div class="container">
  <%= simple_form_for @flat, html: { class: "form-group" } do |form| %>
    <div class="form-group">
      <%= form.input :name, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= form.input :adress, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= form.input :description, as: :text, input_html: { rows: 3, class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= form.input :price_per_night, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <%= form.input :number_of_guests, input_html: { class: "form-control" } %>
    </div>

    <%= form.button :submit, "Update Flat", class: "btn btn-primary mt-3" %>
  <% end %>
</div>

app/views/flats/index.html.erb
<h1 class="mb-4">All flats</h1>

<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-md-4 mb-4">
      <div class="card">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text">Address: <%= flat.adress %></p>
        <p class="card-text">Description: <%= flat.description %></p>
        <p class="card-text">Price per night: € <%= flat.price_per_night %></p>
        <p class="card-text">Number of guests: <%= flat.number_of_guests %></p>
        <div>
          <%= link_to "Show flat info", flat_path(flat), class: "btn btn-success mb-4" %>
          <%= link_to 'Delete Flat', flat_path(flat), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger mb-4"%>
          <%= link_to "Add a new Flat", new_flat_path, class: "btn btn-success mb-4" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <%= link_to "Add a new Flat", new_flat_path, class: "btn btn-success mb-4" %>
</div>

app/views/flats/new.html.erb
<h1>AdD a NeW fLaT</h1>
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :adress %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<h1 class="mb-4"><%= @flat.name %></h1>

<div class="container">
  <div class="row">

    <div class="col-md-4 mb-4">
      <div class="card">
        <h5 class="card-title"><%= @flat.name %></h5>
        <p class="card-text">Address: <%= @flat.adress %></p>
        <p class="card-text">Description: <%= @flat.description %></p>
        <p class="card-text">Price per night: € <%= @flat.price_per_night %></p>
        <p class="card-text">Number of guests: <%= @flat.number_of_guests %></p>
        <div>
          <%= link_to "Edit", edit_flat_path, class: "btn btn-success mb-4" %>
          <%= link_to 'Delete Flat', flat_path(@flat), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "ms-3 text-danger"%>
      </div>
    </div>

  </div>
  <%= link_to "Back to all flats", flats_path, class: "btn btn-success mb-4" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Simple Airbnb" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>